apiVersion: v1
kind: Service
metadata:
  name: statyes-client-ws-svc
spec:
  selector:
    app: statyes-client
  ports:
    - protocol: TCP
      port: 24678
      targetPort: 24678
  type: LoadBalancer