apiVersion: apps/v1
kind: Deployment
metadata:
  name: statyes-db
  labels:
    app: statyes-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statyes-db
  template:
    metadata:
      labels:
        app: statyes-db
    spec:
      containers:
        - name: statyes-db
          image: postgres:14
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: "statyes"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_USER
              value: "root"