apiVersion: v1
kind: PersistentVolume
metadata:
  name: statyes-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/
  persistentVolumeReclaimPolicy: Retain